import Header from "@/components/organisms/Header"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      <Header/>
    </main>
  )
}
